atividades/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'atividades'

urlpatterns = [
    path('minhasatividades',views.AtividadesProfessor.as_view(),name="minhasAtividades"),
    path('atividadadesUOrganica',views.AtividadesCoordenador.as_view(),name="atividadesUOrganica"),
    path('alteraratividade/<int:id>',views.alterarAtividade,name='alterarAtividade'),
    path('sessao/<int:id>',views.inserirsessao,name='inserirSessao'),
    path('eliminaratividade/<int:id>',views.eliminarAtividade,name='eliminarAtividade'),
    path('eliminarsessao/<int:id>',views.eliminarSessao,name='eliminarSessao'),
    path('proporatividade',views.proporatividade,name='proporAtividade'),
    path('validaratividade/<int:id>/<int:action>',views.validaratividade,name='validarAtividade'),
    path('veredificios',views.veredificios,name="verEdificios"),
    path('versalas',views.versalas,name="verSalas"),
    path('verhorarios',views.verhorarios,name="verHorarios"),
    path('verresumo/<int:id>',views.verresumo,name='verResumo'),
    path('confirmar/<int:id>',views.confirmarResumo,name='confirmarResumo'),
    path('atividadesadmin',views.AtividadesAdmin.as_view(),name="atividadesAdmin"),
    path('verdeps',views.verdeps,name="verDepartamentos"),
    path('veruos',views.verfaculdades,name="verFaculdades"),
]

coordenadores/urls.py
from django.urls import path
from django.conf.urls import url
from coordenadores import views

app_name = 'coordenadores'

urlpatterns = [
    path('adicionartarefa/',views.adicionartarefa,name="adicionarTarefa"),
    path('alterartarefa/<int:id>',views.adicionartarefa,name="alterarTarefa"),
    path('consultartarefa/',views.ConsultarTarefas.as_view(),name="consultarTarefa"),
    path('ajax/adicionarsessoes/', views.sessoesAtividade, name='sessoesAtividade'),
    path('ajax/adicionardias/', views.diasAtividade, name='diasAtividade'),
    path('ajax/adicionarcolaboradores/', views.colaboradores, name='colaboradores'),
    path('ajax/tipotarefa/', views.tipoTarefa, name='tipoTarefa'),
    path('ajax/grupoinfo/', views.grupoInfo, name='grupoInfo'),
    path('ajax/diasgrupo/', views.diasGrupo, name='diasGrupo'),
    path('ajax/horariogrupo/', views.horarioGrupo, name='horarioGrupo'),
    path('ajax/origemgrupo/', views.locaisOrigem, name='locaisOrigem'),
    path('ajax/destinogrupo/', views.locaisDestino, name='locaisDestino'),
    path('eliminartarefa/<int:id>',views.eliminartarefa,name="eliminarTarefa"),
    path("atribuircolaborador/<int:id>",views.atribuirColaborador,name="atribuirColaborador"),
]

dia_aberto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from utilizadores.forms import EmailValidationOnForgotPassword
from utilizadores import views
import notifications.urls
from django.conf.urls import handler404,handler500,handler403,handler400
from django.conf import settings # new
from django.conf.urls.static import static # new


handler404 = 'dia_aberto.views.error404'
handler403 = 'dia_aberto.views.error403'
handler400 = 'dia_aberto.views.error400'
handler500 = 'dia_aberto.views.error500'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('atividades/', include('atividades.urls')),
    path('inscricoes/', include('inscricoes.urls')),
    path('utilizadores/', include('utilizadores.urls')),
    path('notificacoes/', include('notificacoes.urls')),
    path('colaboradores/', include('colaboradores.urls')),
    path('configuracao/', include('configuracao.urls')),
    path('coordenadores/', include('coordenadores.urls')),

    path('', views.home, name='home'),

    path('utilizadores/password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('utilizadores/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('utilizadores/password_reset/', auth_views.PasswordResetView.as_view(
        form_class=EmailValidationOnForgotPassword), name='password_reset'),
    path('utilizadores/reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

    path('', include("notifications.urls", namespace='notifications')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

coordenadores/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from datetime import datetime, date,timezone,time
from django.db.models.signals import pre_delete, post_delete
from configuracao.models import *
class Tarefa(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255)  # Field name made lowercase.
    estado = models.CharField(max_length=64)
    coord = models.ForeignKey('utilizadores.Coordenador', models.CASCADE, db_column='CoordenadorUtilizadorID',null=True)  # Field name made lowercase.
    colab = models.ForeignKey('utilizadores.Colaborador', models.SET_NULL, db_column='ColaboradorUtilizadorID',null=True,blank=True)  # Field name made lowercase.
    created_at = models.DateTimeField(auto_now_add=True)
    dia = models.DateField()
    horario = models.TimeField(blank=False, null=False)
    diaaberto = models.ForeignKey('configuracao.Diaaberto', models.CASCADE, db_column='Diaaberto')  # Field name made lowercase.

    def save(self,*args, **kwargs):
        self.diaaberto = Diaaberto.current()
        super(Tarefa, self).save(*args, **kwargs)

    @property
    def tipo(self):
        if TarefaAcompanhar.objects.filter(tarefaid=self.id):
           return "tarefaAcompanhar"
        elif TarefaAuxiliar.objects.filter(tarefaid=self.id):
            return "tarefaAuxiliar"
        elif TarefaOutra.objects.filter(tarefaid=self.id): 
            return "tarefaOutra" 
        return None 


    @property
    def tipo_frontend(self):
        if TarefaAcompanhar.objects.filter(tarefaid=self.id):
           return "Acompanhar"
        elif TarefaAuxiliar.objects.filter(tarefaid=self.id):
            return "Auxiliar"
        elif TarefaOutra.objects.filter(tarefaid=self.id): 
            return "Outra"  

    class Meta:
        db_table = 'Tarefa'
        ordering = ['dia']

    @property
    def eliminar(self):
        if (self.estado == 'Iniciada' and self.dia < date.today()) or\
            self.estado == 'naoConcluida' or\
            self.estado == 'Concluida' or\
            self.estado == 'Cancelada' or\
            self.estado == 'naoAtribuida':
            return True
        return False
        
        
    def getDescription(self):
        if self.tipo == "tarefaAcompanhar":
            tmp = TarefaAcompanhar.objects.get(tarefaid=self.id)
        elif self.tipo == "tarefaAuxiliar":   
            tmp = TarefaAuxiliar.objects.get(tarefaid=self.id)
        else:
            tmp = TarefaOutra.objects.get(tarefaid=self.id)
        return tmp.getDescription()

    def get_tarefa_especifica(self):
        if self.tipo == "tarefaAcompanhar":
            tmp = TarefaAcompanhar.objects.get(tarefaid=self.id)
        elif self.tipo == "tarefaAuxiliar":   
            tmp = TarefaAuxiliar.objects.get(tarefaid=self.id)
        else:
            tmp = TarefaOutra.objects.get(tarefaid=self.id)
        return tmp

    def get_outra_descricao(self):
        tarefa = TarefaOutra.objects.get(tarefaid=self.id)
        if tarefa is not None:
            return tarefa.descricao
        else:
            return ""



class TarefaAcompanhar(models.Model):
    tarefaid = models.OneToOneField(Tarefa, models.CASCADE, db_column='tarefaid', primary_key=True)
    origem = models.CharField(max_length=255, db_column='origem', blank=False, null=False)
    destino = models.CharField(max_length=255, db_column='destino', blank=False, null=False) 
    inscricao = models.ForeignKey('inscricoes.Inscricao', models.CASCADE, db_column='inscricao')
    
    class Meta:
        db_table = 'TarefaAcompanhar'

    def getDescription(self):
        if self.origem != 'Check in':
            local = Espaco.objects.get(id=int(self.origem))
            origem = local.nome
            extra = " da sala "+origem+", no edifício "+ local.edificio.nome
        else:
            extra = " do "+self.origem
        destino = Espaco.objects.get(id=int(self.destino))
        msg = self.tarefaid.nome+extra+" á sala "+destino.nome+", no edifício "+ destino.edificio.nome+", no dia "+self.tarefaid.dia.strftime('%d/%m/%y')\
        +" às "+self.tarefaid.horario.strftime('%H horas e %M minutos')+"."
        return msg


 
    def get_origem(self):
        if self.origem != 'Check in':
            local = Espaco.objects.get(id=int(self.origem))
            origem = local.nome
            return "Sala "+origem+", edifício "+ local.edificio.nome
        else:
            return self.origem

    def get_destino(self):
        destino = Espaco.objects.get(id=int(self.destino))          
        return destino.nome+", edifício "+ destino.edificio.nome


class TarefaAuxiliar(models.Model):
    tarefaid = models.OneToOneField(Tarefa, models.CASCADE, db_column='tarefaid', primary_key=True)
    sessao = models.ForeignKey('atividades.Sessao', models.CASCADE, db_column='sessao')

    class Meta:
        db_table = 'TarefaAuxiliar'
    
    def getDescription(self):
        msg = self.tarefaid.nome+"."
        return msg

def remove_parent(sender,instance, **kwargs):
    tarefaid = instance.tarefaid
    sender.objects.raw('DELETE FROM '+str(sender.__name__) +' WHERE tarefaid ='+str(tarefaid.id))
    Tarefa.objects.get(id=tarefaid.id).delete()

post_delete.connect(remove_parent,sender=TarefaAuxiliar)
post_delete.connect(remove_parent,sender=TarefaAcompanhar)

class TarefaOutra(models.Model):
    tarefaid = models.OneToOneField(Tarefa, models.CASCADE, db_column='tarefaid', primary_key=True)
    descricao = models.TextField(db_column='descricao', blank=False, null=False)

    class Meta:
        db_table = 'TarefaOutra'

    def getDescription(self):
        msg = self.descricao
        return msg

coordenadores/forms.py
from django.forms import * 
from .models import *
from atividades.models import Atividade,Sessao
from utilizadores.models import Colaborador,Coordenador
from configuracao.models import Departamento, Diaaberto, Horario, Espaco
from datetime import datetime,timezone,timedelta
from inscricoes.models import Inscricao,Inscricaosessao

def get_dias():
    try:
        today= datetime.now(timezone.utc) 
        diaaberto=Diaaberto.objects.get(datadiaabertoinicio__gte=today,datadiaabertofim__gte=today)
        diainicio= diaaberto.datadiaabertoinicio.date()
        diafim= diaaberto.datadiaabertofim.date()
        totaldias= diafim-diainicio+timedelta(days=1)
        return [('','Escolha o dia')]+[(diainicio+timedelta(days=d),diainicio+timedelta(days=d))for d in range(totaldias.days)]
    except:
        return [('','Escolha o dia')]

class CustomTimeWidget(TimeInput):

    def __init__(self, attrs=None, format=None, input_type=None, default=None):
        input_type = 'time'
        if input_type is not None:
            self.input_type=input_type
        if attrs is not None:
            self.attrs = attrs.copy()
        else:
            if default is not None:
                self.attrs = {'class': 'input', 'value': default}
        if format is not None:
            self.format = format
        else: 
            self.format = '%H:%M'

def get_atividades_choices(fac):
    return [("",'Escolha a Atividade')]+[(atividade.id,atividade.nome) for atividade in Atividade.tarefas_get_atividades(fac)]

class TarefaAuxiliarForm(Form):
    atividade = ChoiceField(widget=Select(attrs={'onchange':'diasSelect();'}))
    dia = DateField(widget=Select(attrs={'onchange':'sessoesSelect()'}))
    sessao = IntegerField(widget=Select(attrs={'onchange':'colaboradoresSelect()'}))
    colab = CharField(widget=Select(),required=False)

    def __init__(self,facul,*args, **kwargs):
        super(TarefaAuxiliarForm,self).__init__(*args, **kwargs)
        self.fields['atividade'] =  ChoiceField(widget=Select(attrs={'onchange':'diasSelect();'}),choices = get_atividades_choices(facul))

    def save(self,user,id=None):
        data = self.cleaned_data
        estado = 'naoConcluida'
        
        sessao = Sessao.objects.get(id = data.get('sessao'))
        if data.get('colab') == '':
            estado = 'naoAtribuida'
            colab = None
        else:
            colab = Colaborador.objects.get(id = data.get('colab'))
        atividade = Atividade.objects.get(id = data.get('atividade'))
        nome = 'Auxiliar na atividade ' + atividade.nome
        if id is None:
            tarefa=Tarefa.objects.create(nome= nome,estado= estado,coord=user,colab=colab,dia=data.get('dia'),horario=sessao.horarioid.inicio)
            TarefaAuxiliar.objects.create(tarefaid=tarefa,sessao=sessao)
            return tarefa.id
        else:
            Tarefa.objects.filter(id=id).update(nome= nome,estado= estado,coord=user,colab=colab,dia=data.get('dia'),horario=sessao.horarioid.inicio)
            TarefaAuxiliar.objects.filter(tarefaid=id).update(sessao=sessao)
            return id
        


def get_inscricao_choices(facul):
    return [('','Escolha um grupo')]+[(grupo.id,'Grupo '+str(grupo.id)) for grupo in Inscricao.get_tarefa_grupos(facul)]

class TarefaAcompanharForm(Form):
    grupo = ChoiceField(widget=Select(attrs={'onchange':'diasGrupo();grupoInfo();grupoHorario();grupoOrigem();grupoDestino();'}))
    dia = DateField(widget=Select(attrs={'onchange':'grupoHorario()'}))
    horario = TimeField(widget=Select(attrs={'onchange':'grupoOrigem()'}))
    origem = CharField(widget=Select(attrs={'onchange':'grupoDestino()'}))
    destino = CharField(widget=Select(attrs={'onchange':'colaboradoresSelect()'}))
    colab = CharField(widget=Select(),required=False)

    def __init__(self,facul,*args, **kwargs):
        super(TarefaAcompanharForm,self).__init__(*args, **kwargs)
        self.fields['grupo'] =  ChoiceField(widget=Select(attrs={'onchange':'diasGrupo();grupoInfo();grupoHorario();grupoOrigem();grupoDestino();'}),choices = get_inscricao_choices(facul))
    
    def save(self,user,id):
        data = self.cleaned_data
        nome = 'Acompanhar o grupo ' + data.get('grupo')
        grupo = Inscricao.objects.get(id=data.get('grupo'))
        
        destino = Espaco.objects.filter(id=int(data.get('destino'))).first()
        
        estado = 'naoConcluida'
        if data.get('colab') == '':
            estado = 'naoAtribuida'
            colab = None
        else:
            colab = Colaborador.objects.get(id = data.get('colab'))

        origem = data.get('origem')
        

        if  origem != 'Check in':
            local = Espaco.objects.get(id=int(origem))
            origem = str(local.id)  
        
        if id is None:
            tarefa = Tarefa.objects.create(nome= nome,estado= estado,coord=user,colab=colab,dia=data.get('dia'),horario=data.get('horario'))
            TarefaAcompanhar.objects.create(tarefaid=tarefa,origem=origem,destino=str(destino.id),inscricao=grupo)
            return tarefa.id
        else:
            Tarefa.objects.filter(id=id).update(nome= nome,estado= estado,coord=user,colab=colab,dia=data.get('dia'),horario=data.get('horario'))
            TarefaAcompanhar.objects.filter(tarefaid=id).update(origem=origem,destino=str(destino.id),inscricao=grupo)
            return id
    
    


class TarefaOutraForm(Form):
    dia = ChoiceField(widget=Select(attrs={'onchange':'colaboradoresSelect()'}),choices=get_dias())
    horario = TimeField(widget=TimeInput(attrs={'class':'input','type':'time','min':'09:00','max':'18:00','onchange':'colaboradoresSelect();'}))
    descricao = CharField(widget=Textarea(attrs={'class':'textarea'}))
    colab = CharField(widget=Select(),required=False)

    def save(self,user,id=None):
        data = self.cleaned_data
        nome = self.data.get('descricao')
        estado = 'naoConcluida'
        if data.get('colab') == '':
            estado = 'naoAtribuida'
            colab = None
        else:
            colab = Colaborador.objects.get(id = data.get('colab'))
        if id is None:
            tarefa = Tarefa.objects.create(nome= nome[0:18] + '...',estado= estado,coord=user,colab=colab,dia=data.get('dia'),horario=data.get('horario'))
            TarefaOutra(tarefaid=tarefa,descricao=data.get('descricao')).save()
            return tarefa.id
        elif id:
            Tarefa.objects.filter(id=id).update(nome= nome[0:18] + '...',estado= estado,coord=user,colab=colab,dia=data.get('dia'),horario=data.get('horario'))
            TarefaOutra.objects.filter(tarefaid=id).update(descricao=data.get('descricao'))
            return id

coordenadores/templates/coordenadores/criarTarefa.html
{% extends 'app.html' %}
{% block content %}
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><a href="{% url 'home' %}">Início</a></li>
    <li><a href="{% url 'coordenadores:consultarTarefa' %}">Tarefas</a></li>
    {% if  tarefa %}
      <li class="is-active"><a href="">Alterar Tarefa</a></li>
    {% else %}
      <li class="is-active"><a href="">Adicionar Tarefa</a></li>
    {% endif %}
    
  </ul>
</nav>
<div style="padding: 3rem 2vw 1rem">
    <form method="POST" action="">
      {% csrf_token %}
      <nav class="steps is-success">
        <div class="step-item is-completed is-success is-active"> 
        </div>
        <div class="step-item is-completed is-success">
          <div class="step-marker">
              <span class="icon">
                <i class="mdi mdi-account-details mdi-24px"></i>
              </span>
          </div>
          <div class="step-details">
              {% if  tarefa %}
                <p class="step-title">Alterar Tarefa</p>
              {% else %}
                 <p class="step-title">Adicionar Tarefa</p>
              {% endif %}
          </div>
        </div>
        <div class="step-item is-completed is-success is-active"> 
        </div>
      </nav>        
      <div style="padding: 1rem 2vw 0px;" onload="alterarTarefa();">
            <hr>
            <div class="column is-offset-3 is-6">
                <div class="block">
                {% if tarefa %}
                      <h1 class="title is-3 has-text-centered">Tarefa {{tarefa.tipo_frontend}}</h1><input hidden name="tipo" value="{{tarefa.tipo}}">
                {% else %}
                    <div class="field">
                        <label class="label">Tipo de tarefa: </label>
                    </div>
                    <div class="control">
                      <label class="radio" style="margin-right: 1rem;"><input type="radio" name="tipo" value="tarefaAuxiliar"> 
                        <span class="check"></span>
                        <span class="control-label">Auxiliar Atividade</span>
                      </label>
                      <label class="radio" style="margin-right: 1rem;"><input type="radio" name="tipo" value="tarefaAcompanhar"> 
                        <span class="check"></span>
                        <span class="control-label">Acompanhar Participantes</span>
                      </label>
                      <label class="radio" ><input type="radio" name="tipo" value="tarefaOutra"> 
                        <span class="check"></span>
                        <span class="control-label">Outra</span>
                      </label>
                    </div>
                  {% endif %}
                </div>
                <div id="tipoTarefa" >        
                </div>   
                <div class="field" style="padding-top:10px">
                    <label class="label">Colaborador</label>
                    <div class="control">
                        <div class="select is-fullwidth">
                          <select name="colab" id="id_colab">
                            <option value="" selected>Não atribuir</option>
                          </select>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
      </div>
      <div class="column is-8 is-offset-2">
                <div class="level">
                  <div class="level-left">
                    <a href="javascript:history.back()" class="button is-medium is-outlined" type="button">
                      <span>Cancelar</span>
                    </a>
                  </div>
                  <div class="level-right">
                    <button type="submit" class="button is-medium is-success is-outlined is-link">
                      {% if  tarefa %}
                        <span>Alterar Tarefa</span>
                      {% else %}
                        <span>Adicionar Tarefa</span>
                      {% endif %}
                        <span class="icon is-medium">
                          <i class="mdi mdi-check mdi-36px"></i>
                        </span>
                    </button>
                  </div>
                </div>
      </div>
    </form>
  </div>



<style>
    .label {
        font-weight: normal;
    }
    .b-steps .steps .step-items .step-item .step-details .step-title {
        font-size: 1rem;
    }
</style>
{% endblock content %}
{% block scripts %}
<script>
    $(document).ready(function(){
        if ("{{tarefa}}"!="None"){
          var tipo="{{tarefa.tipo}}";
          var tarefa = "{{tarefa.id}}"
          $.ajax({                       
          url: "{% url 'coordenadores:tipoTarefa' %}", 
          method: 'POST',             
          data: {
              'tipo' : tipo,
              'id' : tarefa,
              csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
          },
          success: function (data) {   
            $("#tipoTarefa").html(data); 
            if("{{tarefa.tipo}}"=="tarefaAuxiliar"){
              diasSelect();
              sessoesSelect();
            }
            else if("{{tarefa.tipo}}"=="tarefaAcompanhar"){  
              diasGrupo();
              grupoInfo();
              grupoHorario();
              grupoOrigem();
              grupoDestino();
            }
            colaboradoresSelect();
          }
          });
        }
    });

    $('input:radio').change(function(){
        var tipo=this.value;
        $.ajax({                       
        url: "{% url 'coordenadores:tipoTarefa' %}", 
        method: 'POST',             
        data: {
            'tipo' : tipo,
            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
        },
        success: function (data) {   
          $("#tipoTarefa").html(data);    
        }
      });
      
    });

/*---------------->AuxiliarAtividade<--------------------*/
    function diasSelect(){
      var atividadeId = document.getElementById("id_atividade").value; 
      var tarefa = "{{tarefa.id}}";
      $.ajax({                       
        url: "{% url 'coordenadores:diasAtividade' %}", 
        method: 'POST',             
        data: {
            'atividadeid': atividadeId,
            'tarefa': tarefa,
            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
        },
        success: function (data) {   
          $("#id_dia").html(data);
          $("#id_sessao").html('<option value="">Escolha a sessão</option>');
          $("#id_colab").html('<option value="">Não Atribuir</option>');
        }
      });
    }

    function sessoesSelect(){
      var dia = document.getElementById("id_dia").value; 
      var atividadeId = document.getElementById("id_atividade").value; 
      var tarefa = "{{tarefa.id}}";
      $.ajax({                       
        url: "{% url 'coordenadores:sessoesAtividade' %}", 
        method: 'POST',             
        data: {
            'dia': dia,
            'atividadeid':atividadeId,
            'tarefa': tarefa,
            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
        },
        success: function (data) {   
          $("#id_sessao").html(data);           
        }
      });
    }

    function colaboradoresSelect(){
      var tarefa = "{{tarefa.id}}";

      var dia = document.getElementById("id_dia").value; 
      if(document.getElementById("id_horario"))
        var horario =document.getElementById("id_horario").value;
      else
        var horario="";
      
      if(document.getElementById("id_sessao"))
        var sessao =document.getElementById("id_sessao").value; 
      else
        var sessao = "";
      $.ajax({                       
        url: "{% url 'coordenadores:colaboradores' %}", 
        method: 'POST',             
        data: {
            'tarefa': tarefa,
            'sessao':sessao,
            'horario':horario,
            'dia':dia,
            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
        },
        success: function (data) {   
          $("#id_colab").html(data);           
        }
      });
    }
/*-------------------->EndAuxiliarAtividade<-----------------*/
/*-------------------->Acompanhar Grupo<---------------------*/
    function grupoInfo(){
      var grupo_id = document.getElementById("id_grupo").value;
      var tarefa = "{{tarefa.id}}"
      $.ajax({                       
        url: "{% url 'coordenadores:grupoInfo' %}", 
        method: 'POST',             
        data: {
            'grupo_id': grupo_id,
            'tarefa':tarefa,
            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
        },
        success: function (data) {   
          $("#grupoinfo").html(data);           
        }
      });
    }

    function diasGrupo(){
      var grupo_id = document.getElementById("id_grupo").value;
      var tarefa = "{{tarefa.id}}"
      $.ajax({                       
        url: "{% url 'coordenadores:diasGrupo' %}", 
        method: 'POST',             
        data: {
            'grupo_id': grupo_id,
            'tarefa' : tarefa,
            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
        },
        success: function (data) {   
          $("#id_dia").html(data);  
          $("#id_origem").html('<option value="">Escolha o local de encontro</option>');   
          $("#id_destino").html('<option value="">Escolha o local de destino</option>');            
        }
      });
    }

    function grupoHorario(){
      var dia = document.getElementById("id_dia").value;
      var grupo_id = document.getElementById("id_grupo").value; 
      var tarefa = "{{tarefa.id}}"
      $.ajax({                       
        url: "{% url 'coordenadores:horarioGrupo' %}", 
        method: 'POST',             
        data: {
            'dia': dia,
            'grupo_id' : grupo_id,
            'tarefa': tarefa,
            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
        },
        success: function (data) {   
          $("#id_horario").html(data);           
        }
      });
    }

    function grupoOrigem(){
      var dia = document.getElementById("id_dia").value;
      var grupo_id = document.getElementById("id_grupo").value; 
      var horario = document.getElementById("id_horario").value;
      var tarefa = "{{tarefa.id}}";
      $.ajax({                       
        url: "{% url 'coordenadores:locaisOrigem' %}", 
        method: 'POST',             
        data: {
            'dia': dia,
            'grupo_id' : grupo_id,
            'horario' : horario,
            'tarefa' : tarefa,
            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
        },
        success: function (data) {   
          $("#id_origem").html(data); 
          $("#id_destino").html('<option value="">Escolha o local de destino</option>');          
        }
      });
    }

    function grupoDestino(){
      var dia = document.getElementById("id_dia").value;
      var grupo_id = document.getElementById("id_grupo").value; 
      var horario = document.getElementById("id_horario").value;
      var origem = document.getElementById("id_origem").value;
      var tarefa = "{{tarefa.id}}";
      $.ajax({                       
        url: "{% url 'coordenadores:locaisDestino' %}", 
        method: 'POST',             
        data: {
            'dia': dia,
            'grupo_id' : grupo_id,
            'horario' : horario,
            'tarefa':tarefa,
            'origem':origem,
            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
        },
        success: function (data) {   
          $("#id_destino").html(data);           
        }
      });
    }
/*----------------->EndAcompanharAtividade<--------------*/

</script>
{% endblock scripts %}

coordenadores/templates/coordenadores/grupoInfo.html
<p>{{info.escola.nome}} {{info.ano}}ºano</p>
<p>Responsável {{responsavel.nome}}</p>