atividades/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'atividades'

urlpatterns = [
    path('minhasatividades',views.AtividadesProfessor.as_view(),name="minhasAtividades"),
    path('atividadadesUOrganica',views.AtividadesCoordenador.as_view(),name="atividadesUOrganica"),
    path('alteraratividade/<int:id>',views.alterarAtividade,name='alterarAtividade'),
    path('sessao/<int:id>',views.inserirsessao,name='inserirSessao'),
    path('eliminaratividade/<int:id>',views.eliminarAtividade,name='eliminarAtividade'),
    path('eliminarsessao/<int:id>',views.eliminarSessao,name='eliminarSessao'),
    path('proporatividade',views.proporatividade,name='proporAtividade'),
    path('validaratividade/<int:id>/<int:action>',views.validaratividade,name='validarAtividade'),
    path('veredificios',views.veredificios,name="verEdificios"),
    path('versalas',views.versalas,name="verSalas"),
    path('verhorarios',views.verhorarios,name="verHorarios"),
    path('verresumo/<int:id>',views.verresumo,name='verResumo'),
    path('confirmar/<int:id>',views.confirmarResumo,name='confirmarResumo'),
    path('atividadesadmin',views.AtividadesAdmin.as_view(),name="atividadesAdmin"),
    path('verdeps',views.verdeps,name="verDepartamentos"),
    path('veruos',views.verfaculdades,name="verFaculdades"),
]

colaboradores/urls.py
from django.urls import path, include

from . import views

app_name = 'colaboradores'


urlpatterns = [
    path('consultartarefas', views.consultar_tarefas.as_view(),
         name='consultar-tarefas'),
    path('disponibilidade', views.minha_disponibilidade,
         name='minha-disponibilidade'),
    path('departamentos', views.ver_departamentos,
         name='ver-departamentos'),
    path('preferenciaatividade', views.preferencia_atividade,
         name="preferencia-atividade"),

    path('escolheratividades', views.AtividadesColaborador.as_view(),
         name="escolher-atividades"),
         
    path('atividadesescolhidas', views.AtividadesColaboradorSelecionadas.as_view(),
         name="atividades-escolhidas"),


    path('selecionaratividade/<int:id>', views.selecionar_atividade,
         name="selecionar-atividade"),

     path('retiraratividade/<int:id>', views.retirar_atividade,
         name="retirar-atividade"),

    path('concluirdisponibilidade', views.concluir_disponibilidade,
         name='concluir-disponibilidade'),
    path('concluirtarefa/<int:id>', views.concluir_tarefa, name='concluir-tarefa'),
    path('iniciartarefa/<int:id>', views.iniciar_tarefa, name='iniciar-tarefa'),
    path('cancelartarefa/<int:id>', views.cancelar_tarefa, name='cancelar-tarefa'),
    path('rejeitarcancelamentotarefa/<int:id_notificacao>',
         views.rejeitar_cancelamento_tarefa, name='rejeitar-cancelamento-tarefa'),
    path('validarcancelamentotarefa/<int:id_notificacao>',
         views.validar_cancelamento_tarefa, name='validar-cancelamento-tarefa'),

    path('ajax/addHorarioRow', views.newHorarioRow, name='ajaxAddHorarioRow'),
]

dia_aberto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from utilizadores.forms import EmailValidationOnForgotPassword
from utilizadores import views
import notifications.urls
from django.conf.urls import handler404,handler500,handler403,handler400
from django.conf import settings # new
from django.conf.urls.static import static # new


handler404 = 'dia_aberto.views.error404'
handler403 = 'dia_aberto.views.error403'
handler400 = 'dia_aberto.views.error400'
handler500 = 'dia_aberto.views.error500'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('atividades/', include('atividades.urls')),
    path('inscricoes/', include('inscricoes.urls')),
    path('utilizadores/', include('utilizadores.urls')),
    path('notificacoes/', include('notificacoes.urls')),
    path('colaboradores/', include('colaboradores.urls')),
    path('configuracao/', include('configuracao.urls')),
    path('coordenadores/', include('coordenadores.urls')),

    path('', views.home, name='home'),

    path('utilizadores/password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('utilizadores/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('utilizadores/password_reset/', auth_views.PasswordResetView.as_view(
        form_class=EmailValidationOnForgotPassword), name='password_reset'),
    path('utilizadores/reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

    path('', include("notifications.urls", namespace='notifications')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

inscricoes/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from django.urls import path
from django.views.generic import RedirectView
from . import views

app_name = 'inscricoes'

urlpatterns = [
    path('api/atividades', views.AtividadesAPI.as_view(), name="api-atividades"),
    path('criar', views.CriarInscricao.as_view(),
         name='criar-inscricao'),
    path('<int:pk>/pdf', views.InscricaoPDF,
         name='inscricao-pdf'),
    path('minhasinscricoes', views.MinhasInscricoes.as_view(),
         name='consultar-inscricoes-participante'),
    path('inscricoesdepartamento', views.InscricoesUO.as_view(),
         name='consultar-inscricoes-coordenador'),
    path('inscricoesadmin', views.InscricoesAdmin.as_view(),
         name='consultar-inscricoes-admin'),
    path('<int:pk>', views.ConsultarInscricao.as_view(),
         name='consultar-inscricao'),
    path('<int:pk>/<int:step>', views.ConsultarInscricao.as_view(),
         name='consultar-inscricao'),
    path('alterar/<int:pk>', views.ConsultarInscricao.as_view(), {'alterar': True},
         'alterar-inscricao'),
    path('alterar/<int:pk>/<int:step>', views.ConsultarInscricao.as_view(), {'alterar': True},
         'alterar-inscricao'),
    path('apagar/<int:pk>', views.ApagarInscricao,
         name='apagar-inscricao'),
    path('estatisticas', views.estatisticas,
         name='estatisticas'),
    path('estatisticas/<int:diaabertoid>', views.estatisticas,
         name='estatisticas'),
]

colaboradores/models.py
from django.db import models
#from .views import get_dia_choices


class ColaboradorHorario(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True) 
    colab = models.ForeignKey('utilizadores.Colaborador', models.CASCADE, db_column='ColaboradorUtilizadorID',null=True,blank=True) 
    dia = models.DateField()
    inicio = models.TimeField(db_column='Inicio') 
    fim = models.TimeField(db_column='Fim') 


    class Meta:
        db_table = 'ColaboradorHorario'

    def check_horario(self, dia, inicio, fim):
        return self.colab.get_tarefas(dia, inicio, fim)
        

class Preferencia(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True) 
    colab = models.ForeignKey('utilizadores.Colaborador', models.CASCADE, db_column='ColaboradorUtilizadorID',null=True,blank=True) 
    tipoTarefa = models.CharField(db_column='Tipo', max_length=64) 
    class Meta:
        db_table = 'Preferencia'


class PreferenciaAtividade(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True) 
    preferencia = models.ForeignKey(Preferencia, models.CASCADE, db_column='PreferenciaID',null=True,blank=True) 
    atividade = models.ForeignKey('atividades.Atividade', models.CASCADE, db_column='Atividade',null=True,blank=True) 

    class Meta:
        db_table = 'PreferenciaAtividade'        

colaboradores/forms.py
from django.forms import ModelForm
from .models import *
from utilizadores.models import *
from coordenadores.models import *
from django.forms import *
from django import forms
import time


TIPO = (
    ("Tarefa", "Todos os Tipos"),
    ("tarefaAuxiliar", "Ajudar na Atividade"),
    ("tarefaAcompanhar", "Acompanhar Participantes"),
    ("tarefaOutra", "Outras Tarefas"),
)

ESTADOS = (
    ("", "Todos os Estados"),
    ("Concluida", "Concluída"),
    ("naoConcluida", "Não Concluída"),
    ("Iniciada", "Iniciada"),
    ("Cancelada", "Cancelada"),
)




class TarefaFiltro(Form):
    filtro_tipo = ChoiceField(
        choices=TIPO,
        widget=Select(),
        required=False,
    )

    filtro_estado = ChoiceField(
        choices=ESTADOS,
        widget=Select(),
        required=False,
    )
############################################################## DISPONIBILIDADE ###########################################################

def get_dias():
    try:
        today= datetime.now(timezone.utc) 
        diaaberto=Diaaberto.objects.get(datadiaabertoinicio__gte=today,datadiaabertofim__gte=today)
        diainicio= diaaberto.datadiaabertoinicio.date()
        diafim= diaaberto.datadiaabertofim.date()
        totaldias= diafim-diainicio+timedelta(days=1)
        return [('','Escolha o dia')]+[(diainicio+timedelta(days=d),diainicio+timedelta(days=d))for d in range(totaldias.days)]
    except:
        return [('','Escolha o dia')]


TAREFAS_CHOICES = [
    ("tarefaAuxiliar", "Auxiliar em atividades"),
    ("tarefaAcompanhar", "Acompanhar participantes"),
    ("tarefaOutra", "Outras tarefas"),
]

class PreferenciaTarefasForm(forms.Form):
    tipo_tarefa = forms.MultipleChoiceField(
        required=True,
        widget=forms.CheckboxSelectMultiple,
        choices=TAREFAS_CHOICES,
    )
    def clean(self):
        tarefa_auxiliar = self.cleaned_data.get('tarefaAuxiliar')
        tarefa_acompanhar = self.cleaned_data.get('tarefaAcompanhar')
        tarefa_outra = self.cleaned_data.get('tarefaOutra')
        
        if tarefa_auxiliar == "" and tarefa_acompanhar=="" and tarefa_outra=="":
            raise forms.ValidationError(f'Selecione pelo menos um tipo de tarefa pelo qual tenha preferência ou todas se não tiver nenhuma preferência')
        



class CustomTimeWidget(TimeInput):

    def __init__(self, attrs=None, format=None, input_type=None, default=None):
        input_type = 'time'
        if input_type is not None:
            self.input_type=input_type
        if attrs is not None:
            self.attrs = attrs.copy()
        else:
            if default is not None:
                self.attrs = {'class': 'input', 'value': default}
        if format is not None:
            self.format = format
        else: 
            self.format = '%H:%M'
    

class colaboradorHorarioForm(models.ModelForm):

    class Meta:
        model = ColaboradorHorario
        exclude = ['id','colab']
        widgets = {
			'dia': Select(attrs={'class': 'input'}),
			'inicio': CustomTimeWidget(attrs={'class': 'input'}),
			'fim': CustomTimeWidget(attrs={'class': 'input'}),
        }
    
    def clean(self):

        cleaned_data = super().clean()

        inicio = cleaned_data['inicio']
        fim = cleaned_data['fim']

        if inicio > fim:
            raise forms.ValidationError('O horário de inicio deve ser menor que o horário de fim')
        

def get_atividades_choices(fac):
    return [("",'Escolha a Atividade')]+[(atividade.id,atividade.nome) for atividade in Atividade.tarefas_get_atividades(fac)]    

colaboradores/templates/colaboradores/consultar_tarefas.html
{% extends 'app.html' %}
{% load django_tables2 %}

{% block title %}- Minhas Tarefas{% endblock title %}

{% block content %}

<div class="columns">
    <div class="column is-3">
        <div class="menu">
            <div class="menu-label">
                Filtros Tarefas
            </div>
            <form method="get">
                <div class="field">
                    <div class="control has-icons-left">
                        <input class="input" name="{{ filter.form.nome.name }}"
                            value="{{ filter.form.nome.value|default_if_none:'' }}" type="text" placeholder="Nome">
                        <span class="icon is-left">
                            <i class="mdi mdi-magnify mdi-24px"></i>
                        </span>
                    </div>
                </div>
                <hr>
                <div class="field">
                    <div class="control has-icons-left">
                        <div class="select is-fullwidth">
                            <select name="{{ filter.form.tipo.name }}" value="{{filter.form.tipo.value}}">
                                <option value="">Todos os Tipos</option>
                                <option value="tarefaAuxiliar" {% if filter.form.tipo.value == "tarefaAuxiliar" %}
                                    selected {% endif %}>
                                    Ajudar na Atividade
                                </option>
                                <option value="tarefaAcompanhar" {% if filter.form.tipo.value == "tarefaAcompanhar" %}
                                    selected {% endif %}>
                                    Acompanhar Participantes
                                </option>
                                <option value="tarefaOutra" {% if filter.form.tipo.value == "tarefaOutra" %} selected
                                    {% endif %}>
                                    Outras Tarefas
                                </option>
                            </select>
                        </div>
                        <span class="icon is-left">
                            <i class="mdi mdi-magnify mdi-24px"></i>
                        </span>
                    </div>
                </div>
                <div class="field">
                    <div class="control has-icons-left">
                        <div class="select is-fullwidth">
                            <select name="{{ filter.form.estado.name }}" value="{{filter.form.estado.value}}">
                                <option value="">Todos os Estados</option>
                                <option value="naoConcluida" {% if filter.form.estado.value == "naoConcluida" %}
                                    selected {% endif %}>
                                    Não Concluída
                                </option>
                                <option value="Concluida" {% if filter.form.estado.value == "Concluida" %} selected
                                    {% endif %}>
                                    Concluida
                                </option>
                                <option value="Cancelada" {% if filter.form.estado.value == "Cancelada" %} selected
                                    {% endif %}>
                                    Cancelada
                                </option>
                                <option value="Iniciada" {% if filter.form.estado.value == "Iniciada" %} selected
                                    {% endif %}>
                                    Iniciada
                                </option>
                            </select>
                        </div>
                        <span class="icon is-left">
                            <i class="mdi mdi-magnify mdi-24px"></i>
                        </span>
                    </div>
                </div>
                <div class="field is-grouped">
                    <p class="control is-expanded">
                        <input class="button is-light is-fullwidth" type="reset"
                            onclick="event.preventDefault(); window.location='{% url 'colaboradores:consultar-tarefas' %}';"
                            value="Limpar">
                    </p>
                    <p class="control is-expanded">
                        <button class="button is-primary is-fullwidth" type="submit">
                            <span class="icon">
                                <i class="mdi mdi-magnify"></i>
                            </span>
                            <span>Pesquisar</span>
                        </button>
                    </p>
                </div>
            </form>
        </div>
    </div>
    <div class="column">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a href="{% url 'home' %}">Início</a></li>
                <li class="is-active"><a href="{% url 'colaboradores:consultar-tarefas' %}"
                        aria-current="page">Consultar Tarefas</a></li>
            </ul>
        </nav>
        {% render_table table 'colaboradores/consultar_tarefas_table.html' %}
    </div>
</div>
{% endblock content %}

colaboradores/templates/colaboradores/consultar_tarefas_table.html
{% extends 'bulma_table_details.html' %}
{% load informacao %}

{% block details_content %}
<p>
    <button class="button is-info is-light">{{ date|get_due_date_string:row.record.id }}</button>
</p>
<table>
    <tbody>
        <tr>
            <td><strong>Nome:</strong></td>
            <td>{% if row.record.get_outra_descricao != "" %}{{row.record.get_outra_descricao}}{% else %}{{row.record.nome}}{% endif %}
            </td>
        </tr>
        <tr>
            <td><strong>Tipo de Tarefa:</strong></td>
            <td>
                {% if row.record.tipo == "tarefaAuxiliar" %}
                Ajudar na Atividade
                {% elif row.record.tipo == "tarefaAcompanhar" %}
                Acompanhar Participantes
                {% else %}
                Outras Tarefas
                {% endif %}
            </td>
        </tr>
        {% if row.record.tipo == "tarefaAuxiliar" %}
        <tr>
            <td><strong>Campus:</strong></td>
            <td>{{row.record.get_tarefa_especifica.sessao.atividadeid.espacoid.edificio.campus.nome}}</td>
        </tr>
        <tr>
            <td><strong>Edifício:</strong></td>
            <td>{{row.record.get_tarefa_especifica.sessao.atividadeid.espacoid.edificio.nome}}</td>
        </tr>
        <tr>
            <td><strong>Sala:</strong></td>
            <td>{{row.record.get_tarefa_especifica.sessao.atividadeid.espacoid.nome}}</td>
        </tr>
        <tr>
            <td><strong>Professor Universitário Responsável:</strong></td>
            <td>{{row.record.get_tarefa_especifica.sessao.atividadeid.professoruniversitarioutilizadorid.first_name}}
                {{row.record.get_tarefa_especifica.sessao.atividadeid.professoruniversitarioutilizadorid.last_name}}
            </td>
        </tr>
        {% elif row.record.tipo == "tarefaAcompanhar" %}
        <tr>
            <td><strong>Quem Acompanhar:</strong></td>
            <td><a href="{% url 'inscricoes:inscricao-pdf' row.record.get_tarefa_especifica.inscricao.pk %}">Grupo {{row.record.get_tarefa_especifica.inscricao.get_grupo}} (Clicar para ver detalhes da inscrição)</a></td>
        </tr>
        <tr>
            <td><strong>Origem:</strong></td>
            <td>{{row.record.get_tarefa_especifica.get_origem}}</td>
        </tr>
        <tr>
            <td><strong>Destino:</strong></td>
            <td>{{row.record.get_tarefa_especifica.get_destino}}</td>
        </tr>
        {% endif %}
        <tr>
            <td><strong>Coordenador Responsável:</strong></td>
            <td>{{row.record.coord.first_name}} {{row.record.coord.last_name}}</td>
        </tr>
    </tbody>
</table>

<div class="field is-grouped" style="margin-top: 10px">
    {% if row.record.estado == 'naoConcluida'  %}
    {% if date|tarefa_passou:row.record.id == False %}
    <div class="control">
        <a onclick="alert.warning('<b>Atenção!</b><br><br>Esta tarefa ainda não começou')">

            <button class="button is-link">Iniciar</button>
        </a>
    </div>
    {% else %}
    <div class="control">
        <a href="{% url 'colaboradores:iniciar-tarefa' row.record.id %}">
            <button class="button is-link">Iniciar</button>
        </a>
    </div>
    {% endif %}
    {% endif %}
    {% if row.record.estado == 'Iniciada'  %}
    <div class="control">
        <a href="{% url 'colaboradores:concluir-tarefa' row.record.id %}">
            <button class="button is-link is-light">Concluir</button>
        </a>
    </div>
    {% endif %}
    {% if row.record.estado != 'Cancelada' and row.record.estado != 'Concluida' %}
    <div class="control">
        <a
            onclick="alert.render('Tem a certeza que pretende cancelar esta tarefa?','{% url 'colaboradores:cancelar-tarefa' row.record.id %}')">
            <button class="button is-light">
                Cancelar
            </button>
        </a>
    </div>
    {% endif %}
</div>
{% endblock details_content %}

colaboradores/templates/colaboradores/enviar_notificacao_informativa.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
<head>

  <title>
    Dia Aberto {% block title %} {% endblock title %}
 
  </title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="{% static 'css/bulma.css' %}">
  <link rel="stylesheet" href="{% static 'css/mystyle.css' %}"

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="refresh" content="1; {% url 'colaboradores:consultar-tarefas' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
     <link rel="icon" href="{% static 'img/logo.png' %}"/>
</head>
<body>
<div class="pageloader is-active"><span class="title">{{msg}}</span></div>

</body>
</html>

colaboradores/templates/colaboradores/escolher_atividades.html
{% extends 'app.html' %}
{% block content %}
{% load django_tables2 %}
<div class="columns">
       <div class="column is-3">
{% csrf_token %}


 <form method="get">
            <div class="menu">
                <p class="menu-label">Filtros Atividades</p>
                <ul class="menu-list">
                    <div class="field">
                        <div class="control has-icons-left">
                            <div class="select is-fullwidth">
                                <select name="{{ filter.form.departamento_id.name }}"
                                    value="{{filter.form.departamento_id.value}}" id="id_{{ filter.form.departamento_id.name }}">
                                    <option value="">Qualquer Departamento</option>
                                    {% for value, dep in deps %}
                                        {% if value != "" %}    
                                        <option value="{{ value }}"
                                            {% if value|stringformat:'s' == filter.form.departamento_id.value %} selected
                                            {% endif %}>
                                            {{ dep }}
                                        </option>
                                    {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                            <span class="icon is-left">
                                <i class="mdi mdi-magnify mdi-24px"></i>
                            </span>
                        </div>
                    </div>
                    <div class="field">
                        <div class="control has-icons-left">
                            <div class="select is-fullwidth">
                                <select name="{{ filter.form.tipo.name }}"
                                    value="{{filter.form.tipo.value}}">
                                    <option value="" >Qualquer Tipo</option>
                                    <option value="Tertulia" {% if filter.form.tipo.value == 'Tertulia' %}selected{% endif %}>Tertulia</option>
                                    <option value="Palestra" {% if filter.form.tipo.value == 'Palestra' %}selected{% endif %}>Palestra</option>
                                    <option value="Atividade Laboratorial" {% if filter.form.tipo.value == 'Atividade Laboratorial' %}selected{% endif %}>Atividade Laboratorial</option>
                                </select>
                            </div>
                            
                            <span class="icon is-left">
                                <i class="mdi mdi-magnify mdi-24px"></i>
                            </span>
                            
                        </div>
                    </div>
                
                    <div class="field">
                        <!---->
                        <div class="control has-icons-left is-clearfix">
                            <input class='input' id='id_nome' type='text' name='nome' value="{{filter.form.nome.value|default_if_none:''}}" placeholder="Nome">
                            <span class="icon is-left">
                                <i class="mdi mdi-magnify mdi-24px"></i>
                            </span>
                        </div>
                        <!---->
                    </div>
                </ul>
                <div class='field is-grouped' style='margin-top: 5px'>
                        <p class="control is-expanded">
                            <a type="button" role="button" href="{% url 'colaboradores:preferencia-atividade' %}" class="button is-light is-fullwidth">Limpar</a>
                        </p>
                        <p class="control is-expanded">
                            <button class="button is-primary is-fullwidth" type="submit">
                                <span class="icon">
                                    <i class="mdi mdi-magnify"></i>
                                </span>
                                <span>Pesquisar</span>
                            </button>
                        </p>
                </div>
            </div>     
        </form>
    </div>
    <div class="column">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
              <li><a href="#">Início</a></li>
              <li class="is-active"><a href="#" aria-current="page">Escolher Atividades</a></li>
            </ul>
          </nav>
          
        <a href="{% url 'colaboradores:atividades-escolhidas' %}">
            <button type="button" class="button is-success is-outlined" style="margin-bottom: 1rem;">
            {% comment %} <span class="icon is-small"><i class="mdi mdi-plus"></i></span>  {% endcomment %}
            <span>Ver atividades escolhidas</span>
            </button>
        </a>
        {% render_table table 'colaboradores/tabelacolaborador.html' %}
    </div>
    
</div>
<div style="margin-top:2%;text-align:center;position:center;">
    <a href="{% url 'colaboradores:preferencia-atividade' %}">
        <button type="button" value="Voltar" class="button is-outlined" style="margin-right:5%">Voltar</button>
    </a>
    <a href="{% url 'colaboradores:concluir-disponibilidade' %}">
    <button style="" class="button is-success is-outlined">
        <span>Continuar</span>
    </button>
    </a>
</div>
<style>
.dialog .modal-card .modal-card-body.is-titleless {
    border-top-left-radius: 6px;
    border-top-right-radius: 6px;
}

tr.detail{
    padding:1rem;
}
.table tr.detail{
    -webkit-box-shadow:inset 0 1px 3px #dbdbdb;
    box-shadow:inset 0 1px 3px #dbdbdb;
    background:#fafafa
}
</style>
{% endblock content %}
{% block scripts%}
<script>

 $(document).ready(function(){
            var value_uo= "{{ filter.form.uo_id.value }}";
            var value_dep= "{{filter.form.departamento_id.value}}";
            $.ajax({
            url:"{% url 'colaboradores:ver-departamentos' %}",
            method: 'POST',
            data: {
                'value_uo': value_uo,
                'value_dep': value_dep,
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(), 
            },
            success: function(data){
                $("#id_{{ filter.form.departamento_id.name }}").html(data)
                }
            })
    });


    $("#id_{{ filter.form.uo_id.name }}").change(function()
    {
        var value_uo= $(this).val();
        $.ajax({
            url:"{% url 'colaboradores:ver-departamentos' %}",
            method: 'POST',
            data: {
                'value_uo': value_uo,
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(), 
            },
            success: function(data){
                $("#id_{{ filter.form.departamento_id.name }}").html(data)

            }

        })

    })
</script>
{% endblock scripts%}

colaboradores/templates/colaboradores/preferencia_atividade.html
{% extends 'app.html' %}



{% block title %}- Disponibilidade{% endblock title %}



{% block content %}

<div>
    <nav aria-label="breadcrumbs" class="breadcrumb">
        <ul>
            <li><a href="{% url 'home' %}">Início</a></li>
            <li class="is-active"><a href="{% url 'colaboradores:preferencia-atividade' %}">Disponibilidade</a></li>
        </ul>
    </nav>
<div style="padding: 3rem 2vw 1rem">
    <div class="steps is-success">

        <div class="step-item is-completed is-success">

            <div class="step-marker">

                <span class="icon">

                    <i class="mdi mdi-circle-edit-outline mdi-24px"></i>

                </span>

            </div>

            <div class="step-details">

                <p class="step-title">Minha Disponibilidade</p>

            </div>

        </div>

        <div class="step-item is-success">

            <div class="step-marker">

                <span class="icon">

                    <i class="mdi mdi-flask mdi-24px"></i>

                </span>

            </div>



            <div class="step-details">

                <p class="step-title">Preferência de Atividade</p>

            </div>

        </div>



        <div class="step-item is-success">

            <div class="step-marker">

                <span class="icon">

                    <i class="mdi mdi-check"></i>

                </span>

            </div>

            <div class="step-details">

                <p class="step-title">Concluir</p>

            </div>

        </div>

    </div>
</div>


    <div style="margin-bottom:5%;margin-top:5%;">
        <h2 class="title is-5" style="text-align: center;">Poderá escolher as atividades no qual pretende auxiliar
            enviar</h2>
    </div>
    <div class="columns is-mobile is-centered">
        <div class="column is-narrow">
            <div class="buttons has-addons">

                <a href="{% url 'colaboradores:escolher-atividades' %}">
                    <button class="button">Escolher atividades</button>
                </a>
                <a href="{% url 'colaboradores:atividades-escolhidas' %}">
                    <button class="button">Ver atividades escolhidas</button>
                </a>
                <a href="{% url 'colaboradores:concluir-disponibilidade' %}">
                    <button class="button">Confirmar disponibilidade</button>
                </a>
            </div>
        </div>
    </div>
</div>
<a href="{% url 'colaboradores:minha-disponibilidade' %}">
    <button type="button" value="Voltar" class="button is-outlined"
        style="margin-left: 10%;margin-top:10%;">Voltar</button>
</a>
</div>
{% endblock content %}