atividades/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'atividades'

urlpatterns = [
    path('minhasatividades',views.AtividadesProfessor.as_view(),name="minhasAtividades"),
    path('atividadadesUOrganica',views.AtividadesCoordenador.as_view(),name="atividadesUOrganica"),
    path('alteraratividade/<int:id>',views.alterarAtividade,name='alterarAtividade'),
    path('sessao/<int:id>',views.inserirsessao,name='inserirSessao'),
    path('eliminaratividade/<int:id>',views.eliminarAtividade,name='eliminarAtividade'),
    path('eliminarsessao/<int:id>',views.eliminarSessao,name='eliminarSessao'),
    path('proporatividade',views.proporatividade,name='proporAtividade'),
    path('validaratividade/<int:id>/<int:action>',views.validaratividade,name='validarAtividade'),
    path('veredificios',views.veredificios,name="verEdificios"),
    path('versalas',views.versalas,name="verSalas"),
    path('verhorarios',views.verhorarios,name="verHorarios"),
    path('verresumo/<int:id>',views.verresumo,name='verResumo'),
    path('confirmar/<int:id>',views.confirmarResumo,name='confirmarResumo'),
    path('atividadesadmin',views.AtividadesAdmin.as_view(),name="atividadesAdmin"),
    path('verdeps',views.verdeps,name="verDepartamentos"),
    path('veruos',views.verfaculdades,name="verFaculdades"),
]

configuracao/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'configuracao'

urlpatterns = [

    #-diaAberto
    path('diasabertos', views.viewDays.as_view(), name='diasAbertos'),
    path('editardia/<int:id>', views.newDay, name='editarDia'),
    path('inserirdiaaberto', views.newDay,name='novoDia' ),
    path('deldia/<int:id>', views.delDay, name='eliminarDia'),
    #path('daysjson', views.view_days_as_json, name='daysjson'),

    #-almoco
    path('menus',views.verMenus.as_view(), name='verMenus'),
    path('delmenu/<int:id>', views.delMenu, name='eliminarMenu'),
    path('editarmenu/<int:id>',views.newMenu, name='editarMenu'),
    path('novomenu', views.newMenu, name='novoMenu'),
    #-Transporte
    path('transportes', views.verTransportes.as_view(), name='verTransportes'),
    path('criartransporte', views.criarTransporte, name='criarTransporte'),
    path('editartransporte/<int:id>', views.criarTransporte, name='editarTransporte'),
    path('atribuirtransporte/<int:id>', views.atribuirTransporte, name='atribuirTransporte'),
    path('eliminaratribuicao/<int:id>', views.eliminarAtribuicao, name='eliminarAtribuicao'),
    path('eliminartransporte/<int:id>', views.eliminarTransporte, name='eliminarTransporte'),
    #-Utility
    path('imagens/edificio/<int:id>', views.verEdificioImagem, name='verEdificioImagem'),
    path('edificios', views.verEdificios.as_view(), name='verEdificios'),
    path('adicionaredificio', views.configurarEdificio, name='adicionarEdificio'),
    path('editaredificio/<int:id>', views.configurarEdificio, name='editarEdificio'),
    path('eliminaredificio/<int:id>', views.eliminarEdificio,name='eliminarEdificio'),

    path('uos', views.verUOs.as_view(), name='verUOs'),
    path('adicionaruo', views.configurarUO, name='adicionarUO'),
    path('editaruo/<int:id>', views.configurarUO, name='editarUO'),
    path('eliminaruo/<int:id>', views.eliminarUO,name='eliminarUO'),

    path('temas', views.verTemas.as_view(), name='verTemas'),
    path('adicionarTema', views.configurarTema, name='adicionarTema'),
    path('editarTema/<int:id>', views.configurarTema, name='editarTema'),
    path('eliminarTema/<int:id>', views.eliminarTema,name='eliminarTema'),

    path('departamentos', views.verDepartamentos.as_view(), name='verDepartamentos'),
    path('adicionarDepartamento', views.configurarDepartamento, name='adicionarDepartamento'),
    path('editarDepartamento/<int:id>', views.configurarDepartamento, name='editarDepartamento'),
    path('eliminarDepartamento/<int:id>', views.eliminarDepartamento,name='eliminarDepartamento'),

    path('cursos', views.verCursos.as_view(), name='verCursos'),
    path('adicionarCurso', views.configurarCurso, name='adicionarCurso'),
    path('editarCurso/<int:id>', views.configurarCurso, name='editarCurso'),
    path('eliminarCurso/<int:id>', views.eliminarCurso,name='eliminarCurso'),

    #ajax ----------
    path('ajax/getDias', views.getDias, name='getDias'),
    path('ajax/addHorarioRow', views.newHorarioRow, name='ajaxAddHorarioRow'),
    path('ajax/addPratoRow', views.newPratoRow, name='ajaxAddPratoRow'),
    path('ajax/addEspacoRow', views.newEspacoRow, name='ajaxAddEspacoRow'),
    path('ajax/addUORow', views.newUORow, name='ajaxAddUORow'),
    path('ajax/addDepartamentoRow', views.newDepartamentoRow, name='ajaxAddDepartamentoRow'),
    path('ajax/addCursoRow', views.newCursoRow, name='ajaxAddCursoRow'),

]

dia_aberto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from utilizadores.forms import EmailValidationOnForgotPassword
from utilizadores import views
import notifications.urls
from django.conf.urls import handler404,handler500,handler403,handler400
from django.conf import settings # new
from django.conf.urls.static import static # new


handler404 = 'dia_aberto.views.error404'
handler403 = 'dia_aberto.views.error403'
handler400 = 'dia_aberto.views.error400'
handler500 = 'dia_aberto.views.error500'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('atividades/', include('atividades.urls')),
    path('inscricoes/', include('inscricoes.urls')),
    path('utilizadores/', include('utilizadores.urls')),
    path('notificacoes/', include('notificacoes.urls')),
    path('colaboradores/', include('colaboradores.urls')),
    path('configuracao/', include('configuracao.urls')),
    path('coordenadores/', include('coordenadores.urls')),

    path('', views.home, name='home'),

    path('utilizadores/password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('utilizadores/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('utilizadores/password_reset/', auth_views.PasswordResetView.as_view(
        form_class=EmailValidationOnForgotPassword), name='password_reset'),
    path('utilizadores/reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

    path('', include("notifications.urls", namespace='notifications')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

configuracao/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.core import validators
from datetime import datetime,timedelta, timezone
import time
from time import mktime
from datetime import datetime,timedelta, timezone, time as datetime_time
from utilizadores.models import Coordenador
from django.shortcuts import redirect
from django.utils.safestring import mark_safe
from django.urls.base import reverse
from django.utils.html import escape
from django.core.exceptions import NON_FIELD_ERRORS
class Transporte(models.Model):
    # Field name made lowercase.
    id = models.AutoField(db_column='ID', primary_key=True)
    # Field name made lowercase.
    identificador = models.CharField(db_column='Identificador', max_length=32)
    diaaberto = models.ForeignKey(
        'Diaaberto', models.CASCADE, db_column='diaAberto')
    dia = models.DateField(db_column="Dia", blank=False, null=False)
    def __str__(self):
        return str(self.identificador)
    class Meta:
        db_table = 'Transporte'

class Transportehorario(models.Model):
    # Field name made lowercase.
    id = models.AutoField(db_column='ID', primary_key=True)
    # Field name made lowercase.
    choices = {
        ('Penha','Penha'),
        ('Terminal','Terminal'),
        ('Gambelas','Gambelas'),
    }
    origem = models.CharField(db_column='Origem', max_length=32, blank=True, null=False, choices=choices)
    # Field name made lowercase.
    chegada = models.CharField(db_column='Chegada', max_length=32, blank=True, null=False, choices=choices)
    # Field name made lowercase.

    horaPartida = models.TimeField(db_column="HoraPartida", blank=False, null=False)
    horaChegada = models.TimeField(db_column="HoraChegada", blank=False, null=False)

    transporte = models.ForeignKey(
        Transporte, models.CASCADE, db_column='Transporte')

    def __str__(self):
        return self.origem + " - " + self.chegada + ' Horas: ' + str(self.horaChegada) + ' - ' + str(self.horaPartida) + ' ' + str(self.transporte)
    @property
    def get_identifier(self):
        return self.transporte.identificador

    @property
    def get_capacidade(self):
        return Transporteuniversitario.objects.get(transporte=self.transporte).capacidade

    @property
    def get_trip_time(self):
        return datetime_time.strftime(self.horaPartida, "%H:%M") + ' - ' + datetime_time.strftime(self.horaChegada, "%H:%M")
    
    def trip(self):
        return str(self.origem) + ' - ' + str(self.chegada)
    class Meta:
        db_table = 'TransporteHorario'

class Transporteuniversitario(models.Model):
    # Field name made lowercase.
    transporte = models.OneToOneField(
        Transporte, models.CASCADE, db_column='Transporte', primary_key=True)
    # Field name made lowercase.
    capacidade = models.IntegerField(db_column='Capacidade')
    def __str__(self):
        return str(self.transporte.id) + ' ' + str(self.capacidade)
    class Meta:
        db_table = 'TransporteUniversitario'


class Diaaberto(models.Model):
    # Field name made lowercase.
    precoalunos = models.FloatField(db_column='PrecoAlunos')
    # Field name made lowercase.
    precoprofessores = models.FloatField(
        db_column='PrecoProfessores', blank=True, null=True)
    # Field name made lowercase.
    id = models.AutoField(db_column='ID', primary_key=True)
    # Field name made lowercase.
    enderecopaginaweb = models.CharField(
        db_column='EnderecoPaginaWeb', max_length=255)
    # Field name made lowercase.
    descricao = models.TextField(db_column='Descricao')
    # Field name made lowercase.
    emaildiaaberto = models.CharField(
        db_column='EmailDiaAberto', max_length=255)
    ano = models.IntegerField(db_column='Ano')  # Field name made lowercase.
    # Field name made lowercase.
    datadiaabertoinicio = models.DateTimeField(db_column='DataDiaAbertoInicio')
    # Field name made lowercase.
    datadiaabertofim = models.DateTimeField(db_column='DataDiaAbertoFim')
    # Field name made lowercase.
    datainscricaoatividadesinicio = models.DateTimeField(
        db_column='DataInscricaoAtividadesInicio')  
    # Field name made lowercase.
    datainscricaoatividadesfim = models.DateTimeField(
        db_column='DataInscricaoAtividadesFim')
    # Field name made lowercase.
    datapropostasatividadesincio = models.DateTimeField(
        db_column='DataPropostasAtividadesIncio')
    # Field name made lowercase.
    dataporpostaatividadesfim = models.DateTimeField(
        db_column='DataPorpostaAtividadesFim')
    # Field name made lowercase.
    administradorutilizadorid = models.ForeignKey(
        'utilizadores.Administrador', models.SET_NULL, db_column='AdministradorUtilizadorID',null=True)
    # Field name made lowercase.
    escalasessoes = models.TimeField(db_column='EscalaSessoes')

    def session_times(self):

        start_time  = self.datadiaabertoinicio.time()
        end_time = self.datadiaabertofim.time()
        start_time_as_seconds = (start_time.hour * 60 + start_time.minute) * 60
        end_time_as_seconds = (end_time.hour * 60 + end_time.minute) * 60
        time_lunch_end = 50400
        return [
            (time.strftime('%H:%M', time.gmtime(start_time_as_seconds + (n*self.escalasessoes.minute*60))))
                for n in range(int((43200 - start_time_as_seconds)/(self.escalasessoes.minute*60)))
        ] + [
            (time.strftime('%H:%M', time.gmtime(time_lunch_end + (n*self.escalasessoes.minute*60))))
                for n in range(int((end_time_as_seconds - time_lunch_end)/(self.escalasessoes.minute*60))+1)
        ]



    def days_as_dict(self):
        data_inicio = self.datadiaabertoinicio
        data_fim = self.datadiaabertofim
        total_dias= data_fim-data_inicio+timedelta(days=1)
        return [{
                    'key':	str( (data_inicio+timedelta(days=d)).date()),
                    'value':	str((data_inicio+timedelta(days=d)).date())
                } for d in range(total_dias.days)
            ]

    def days_as_tuples(self):
        data_inicio = self.datadiaabertoinicio
        data_fim = self.datadiaabertofim
        total_dias= data_fim-data_inicio+timedelta(days=1)
        return [(
                    str( (data_inicio+timedelta(days=d)).date()),
                    str((data_inicio+timedelta(days=d)).date())
                ) for d in range(total_dias.days)
            ]
    @staticmethod
    def current():
        now = datetime.now(timezone.utc)
        qs = Diaaberto.objects.filter(ano=now.year,datadiaabertofim__gte=now)
        if qs.exists():
            return qs.first()
        else: return None

    @staticmethod
    def singup_open():
        now = datetime.now(timezone.utc)
        current = Diaaberto.current()
        if current is not None:
            return current.datainscricaoatividadesinicio <= now and current.datainscricaoatividadesfim > now
        else: return False
    @staticmethod
    def submit_activities_open():
        now = datetime.now(timezone.utc)
        current = Diaaberto.current()
        if current is not None:
            return current.datapropostasatividadesincio <= now and current.dataporpostaatividadesfim > now
        else: return False

    def days_as_array(self):
        data_inicio = self.datadiaabertoinicio
        data_fim = self.datadiaabertofim
        total_dias= data_fim-data_inicio+timedelta(days=1)
        return [(
                    (data_inicio+timedelta(days=d)).date()
                )  for d in range(total_dias.days)
            ]
            
    def __str__(self):
        return str(self.ano)
    class Meta:
        db_table = 'DiaAberto'


class Menu(models.Model):
    # Field name made lowercase.
    id = models.AutoField(db_column='ID', primary_key=True)
    # Field name made lowercase.
    horarioid = models.ForeignKey(
        'Horario', models.CASCADE, db_column='HorarioID')
    campus = models.ForeignKey(
        'Campus', models.CASCADE, db_column='Campus')
    diaaberto = models.ForeignKey(
        'Diaaberto', models.CASCADE, db_column='diaAberto')
    dia = models.DateField(db_column='Dia')

    def pratos_(self):
        return Prato.objects.filter(menuid=self)

    def __str__(self):
        return str(self.campus.nome) + ' ' + str(self.diaaberto.ano)
    class Meta:
        db_table = 'Menu'
        unique_together = ['campus','diaaberto','dia']





class Prato(models.Model):
    # Field name made lowercase.
    id = models.AutoField(db_column='ID', primary_key=True)
    # Field name made lowercase.
    prato = models.CharField(db_column='Prato',max_length=255, blank=False, null=False)
    # Field name made lowercase.
    tipos = [
        ('Carne',"Carne"),
        ('Peixe','Peixe'),
        ('Vegetariano', 'Vegetariano'),
        ('Sobremesa', 'Sobremesa'),
    ]
    tipo = models.CharField(
        choices=tipos,db_column='Tipo', max_length=255, blank=False, null=False)
    # Field name made lowercase.
    nrpratosdisponiveis = models.IntegerField(db_column='NrPratosDisponiveis',blank=False, null=False)


    # Field name made lowercase.
    menuid = models.ForeignKey(Menu, models.CASCADE, db_column='MenuID')

    def __str__(self):
        return (self.prato)
    class Meta:
        db_table = 'Prato'


class Espaco(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=False)  # Field name made lowercase.

dia_aberto/views.py
from django.shortcuts import redirect
from django.core.exceptions import PermissionDenied


def error404(request, exception):
    return redirect('utilizadores:mensagem', 404)
def error500(request):
    return redirect('utilizadores:mensagem', 500)
def error403(request, exception):
    return redirect('utilizadores:mensagem', 403)
def error400(request, exception):
    return redirect('utilizadores:mensagem', 400)            

configuracao/templates/configuracao/criarUOs.html
{% extends 'app.html' %}
{% load static %}
{% block content %}
{% load configuracao_tags %}
<nav class="breadcrumb" aria-label="breadcrumbs">
	<ul>
	<li><a href="{% url 'home' %}">Início</a></li>
	<li><a href="{% url 'configuracao:verEdificios' %}">Edificios</a></li>
	</ul>
</nav>
<div style="padding: 3rem 2vw 1rem">
	<form method="POST" action="">
		<div id="id_removed_rows" style="display:none;"></div>
		{% csrf_token %}
    {% if form.non_field_errors %}
      <article class="message is-danger">
        <div class="message-body">
          <p style="text-align: center;">
          {% for error in form.non_field_errors %}
            <strong>{{ error|escape }}</strong>
          {% endfor %}
          </p>
        </div>
      </article>
    {% endif %}
		<div class="b-steps">
			<section class="step-content">
				<div class="step-item">
					<div style="padding: 1rem 2vw 0px">
						<h2 class="title has-text-grey is-uppercase" style="font-size: 0.9rem">Unidades Organicas</h2>
						<div class='table'>
							<div class='table-wrapper'>
								{{formset.management_form}}
								<table class="table has-mobile-cards is-hoverable is-fullwidth" id='table01'>
									<thead>
										<tr>
											<th style="cursor: pointer;">Nome</th>
											<th style="cursor: pointer;">Sigla</th>
											<th style="cursor: pointer">Campus</th>
										</tr>
									</thead>
									<tbody id='tableBody-01'>
									{% for form in formset %}
									{{form.non_field_errors}}
										<tr>
											{{form.id}}
											{% for field in form.visible_fields  %}
												{% if field.name == "campusid" %}
												<td data-label="{{field.label}}">
													<div class="select">
														{{field|force_required|safe}}
													</div>
												</td>
												{% elif field.name != "DELETE" %}
													{% for error in field.errors %}
														<div class="alert alert-danger">
															<strong>{{field.label|escape}} {{ error|escape }}</strong>
														</div>
													{% endfor %}
													
														<td data-label="{{field.label}}">
															{{field|force_required|safe}}
														</td>
													
												{% endif %}
											{% endfor %}
										</tr>
									{% endfor %}
									</tbody>
								</table>
								{% if allowMore == True %}
								<a role="button" type="button" class="button" id="add-more-rows">
									<span>Adicionar Linha</span>
									<span class="icon is-small">
										<i class="mdi mdi-plus mdi-24px"></i>
									</span>
								</a>
								{% endif %}
								{% if allowDelete == True %}
								<a id="del-row" role="button" type="button" class="button">
									<span>Remover Linha</span>
									<span class="icon is-small">
										<i class="mdi mdi-trash-can-outline mdi-24px" style="color: #ff0000"></i>
									</span>
								</a>
								{% endif %}
							</div>
						</div>
					</div>
					<hr>
					<div class="column is-8 is-offset-2">
						<div class="level">
							<div class="level-left">
								<a class="button is-large is-outlined" type="button" href="{% url 'configuracao:verUOs' %}">
								<span>Cancelar</span>
								</a>
							</div>
							<div class="level-right">
								<button class="button is-large is-success is-outlined is-link" type="submit">
									<span>Confirmar</span>
									<span class="icon is-medium">
										<i class="mdi mdi-check mdi-36px"></i>
									</span>
								</button>
							</div>
						</div>
					</div>
				</div>
			</section>
		</div>
	</form>
</div>

<style>
	.label {
	font-weight: normal;
}
.b-steps .steps .step-items .step-item .step-details .step-title {
	font-size: 1rem;
}
</style>
{% endblock content %}
{% block scripts %}
<script>
	$("#add-more-rows").click(function(){
	var value = $("#id_form-TOTAL_FORMS").val();
	value = Number(value) + Number('1');
	document.getElementById("id_form-TOTAL_FORMS").value = value;
	$.ajax({
		url: "{% url 'configuracao:ajaxAddUORow' %}",
		method: "POST",
		data: {
			'extra': value,
			csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
		},
		success: function(data){
			$("#tableBody-01").append(data);
		}
	});
})
$('#del-row').click(function(e){
	var value = $("#id_form-TOTAL_FORMS").val();
	var initial = $("#id_form-INITIAL_FORMS").val();
	var rowCount = $('#tableBody-01 tr').length;
	if(Number(value) > Number(initial) && Number(value) > 1) {
		$('#table01 tr:last').remove();
		value = Number(value) - Number('1');
		document.getElementById("id_form-TOTAL_FORMS").value = value;
	} else if(rowCount > 1){
		var id = Number($('#table01 tr:last input').attr('id').split('-')[1])
		var form_delete = 'form-'+id+'-DELETE';
		var delete_ = "<input type='hidden' name='"+form_delete+"' id='id_"+form_delete+"' value='on'>";
		$('#table01 tr:last').append(delete_);
		$('#table01 tr:last').hide();
		$('#table01 tr:last').appendTo("#id_removed_rows");
	} else {
		alert.warning("Não pode eliminar todas as linhas");
	}
})
</script>
{% endblock scripts %}

configuracao/templates/configuracao/listaCurso.html
{% extends 'app.html' %}
{% block content %}
{% load l10n %}
{% load configuracao_tags %}
{% load django_tables2 %}
<div class="columns">
    <div class="column is-3">
        <form method="get">
            <div class="menu">
                <p class="menu-label">Filtros Tema</p>
                <ul class="menu-list">
                    <div class="field">
                        <!---->
                        <div class="control has-icons-left is-clearfix">
                            <input class='input' id='id_nome' type='text' name='nome' value="{{filter.form.nome.value|default_if_none:''}}" placeholder="Nome">
                            <span class="icon is-left">
                                <i class="mdi mdi-magnify mdi-24px"></i>
                            </span>
                        </div>
                        <!---->
                    </div>
                    <div class="field">
                        <!---->
                        <div class="control has-icons-left is-clearfix">
                            <input class='input' id='id_sigla' type='text' name='sigla' value="{{filter.form.sigla.value|default_if_none:''}}" placeholder="Sigla">
                            <span class="icon is-left">
                                <i class="mdi mdi-magnify mdi-24px"></i>
                            </span>
                        </div>
                        <!---->
                    </div>
                    <div class="field">
                        <div class="control has-icons-left">
                            <div class="select is-fullwidth">
                                <select name="{{ filter.form.unidadeorganicaid.name }}"
                                    value="{{filter.form.unidadeorganicaid.value}}">
                                    <option value="">Qualquer Faculdade</option>
                                    {% for value, fac in faculdades %}
                                        {% if value != "" %}
                                        <option value="{{ value }}"
                                            {% if value|stringformat:'s' == filter.form.unidadeorganicaid.value %} selected
                                            {% endif %}>
                                            {{ fac }}
                                        </option>
                                    {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                            <span class="icon is-left">
                                <i class="mdi mdi-magnify mdi-24px"></i>
                            </span>
                        </div>
                    </div>
                </ul>
                <div class='field is-grouped' style='margin-top: 5px'>
                        <p class="control is-expanded">
                            <a type="button" class="button is-light is-fullwidth" role="button" href="{% url 'configuracao:verTemas' %}">Limpar</a>
                        </p>
                        <p class="control is-expanded">
                            <button class="button is-primary is-fullwidth" type="submit">
                                <span class="icon">
                                    <i class="mdi mdi-magnify"></i>
                                </span>
                                <span>Pesquisar</span>
                            </button>
                        </p>
                </div>
            </div>     
        </form>
    </div>
    <div class="column">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
              <li><a href="{% url 'home' %}">Início</a></li>
              <li class="is-active"><a href="#" aria-current="page">Cursos</a></li>
            </ul>
          </nav>
        <a class="button is-success is-outlined" type="button" style="margin-bottom:0.5rem" href="{% url 'configuracao:adicionarCurso'%}">     
            <span class="icon is-small">
                <i class="mdi mdi-plus"></i>
            </span>
            <span>Configurar Cursos</span>
        </a>   
        
        {% render_table table %}

    </div>
</div>
{% endblock content %}
{% block scripts %}
{% endblock scripts %}

configuracao/templates/configuracao/listaMenu.html
{% extends 'app.html' %}
{% block content %}
{% load l10n %}
{% load django_tables2 %}
<div class="columns">
    <div class="column is-3">
        <form method="get">
            <div class="menu">
                <p class="menu-label">Filtros Unidade Organica</p>
                <ul class="menu-list">
                    <div class="field">
                        <!---->
                        <div class="control has-icons-left is-clearfix">
                            <input class='input' id='id_dia' type='date' name='dia' value="{{filter.form.dia.value|default_if_none:''}}" >
                            <span class="icon is-left">
                                <i class="mdi mdi-magnify mdi-24px"></i>
                            </span>
                        </div>
                        <!---->
                    </div>
                    <div class="field">
                        <div class="control has-icons-left">
                            <div class="select is-fullwidth">
                                <select name="{{ filter.form.campusid.name }}"
                                    value="{{filter.form.campusid.value}}">
                                    <option value="">Qualquer Campi</option>
                                    {% for value, campus in campi %}
                                        {% if value != "" %}
                                        <option value="{{ value }}"
                                            {% if value|stringformat:'s' == filter.form.campusid.value %} selected
                                            {% endif %}>
                                            {{ campus }}
                                        </option>
                                    {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                            <span class="icon is-left">
                                <i class="mdi mdi-magnify mdi-24px"></i>
                            </span>
                        </div>
                    </div>
                </ul>
                <div class='field is-grouped' style='margin-top: 5px'>
                        <p class="control is-expanded">
                            <a type="button" role="button" href="{% url 'configuracao:verMenus' %}" class="button is-light is-fullwidth">Limpar</a>
                        </p>
                        <p class="control is-expanded">
                            <button class="button is-primary is-fullwidth" type="submit">
                                <span class="icon">
                                    <i class="mdi mdi-magnify"></i>
                                </span>
                                <span>Pesquisar</span>
                            </button>
                        </p>
                </div>
            </div>     
        </form>    
    </div>
    <div class="column">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
              <li><a href="{% url 'home' %}">Início</a></li>
              <li class="is-active"><a href="#" aria-current="page">Menus</a></li>
            </ul>
          </nav>
        <a class="button is-success is-outlined" type="button" style="margin-bottom:0.5rem" href="{% url 'configuracao:novoMenu'%}">     
            <span class="icon is-small">
                <i class="mdi mdi-plus"></i>
            </span>
            <span>Novo Menu</span>
        </a>   

        {% render_table table 'configuracao/verMenusTabela.html' %}
    </div>
</div>
{% endblock content %}
{% block scripts %}
{% endblock scripts %}